name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code again for the deployment job
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Vercel CLI
    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Set up environment variables
      run: |
        echo "NEO4J_URI=${{ secrets.NEO4J_URI }}" >> .env
        echo "NEO4J_USER=${{ secrets.NEO4J_USER }}" >> .env
        echo "NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env


    - name: Deploy to Vercel
      run: |
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
